//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JukeBox.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryDetail
    {
        public long LibraryDetailID { get; set; }
        public long FK_LibraryID { get; set; }
        public short FK_LibraryStatusID { get; set; }
        public string LibraryDetailName { get; set; }
        public string FilePath { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual Library Library { get; set; }
        public virtual LibraryStatu LibraryStatu { get; set; }
        public virtual User User { get; set; }
    }
}
