//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JukeBox.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionCategoryMap
    {
        public int PromotionCategoryMapId { get; set; }
        public int FK_ClientID { get; set; }
        public int FK_PromotionCategoryId { get; set; }
        public bool Enabled { get; set; }
    }
}
