//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JukeBox.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.CustomerTransactions = new HashSet<CustomerTransaction>();
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public long PurchaseID { get; set; }
        public long FK_LibraryID { get; set; }
        public decimal PurchaseAmount { get; set; }
        public System.DateTime PurchaseDateTime { get; set; }
        public short PurchaseItemNumber { get; set; }
        public int FK_UserID { get; set; }
        public int FK_CustomerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerTransaction> CustomerTransactions { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual Library Library { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
