//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JukeBox.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public long PurchaseDetailID { get; set; }
        public Nullable<long> FK_PurchaseID { get; set; }
        public Nullable<long> FK_LibraryDetailID { get; set; }
        public Nullable<decimal> PurchaseAmount { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> FK_CustomerID { get; set; }
    
        public virtual LibraryDetail LibraryDetail { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
