//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JukeBox.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleUserMap
    {
        public int RoleUserMapID { get; set; }
        public int FK_UserID { get; set; }
        public short FK_RoleID { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
    }
}
